server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: data-analysis
  mvc:
    path-match:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #    default-property-inclusion: non_null
  servlet:
    multipart:
      #单文件最大容量
      max-file-size: 10MB
      #多文件最大容量
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host:
      password:
      port: 6379
      database: 0
      timeout: 10000
      lettuce:
        pool:
          max-active: 600
          max-idle: 300
          max-wait: 10000

mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true

springfox:
  documentation:
    enabled: false

management:
  endpoint:
    refresh:
      access: UNRESTRICTED
  endpoints:
    web:
      exposure:
        include: refresh

logging:
  level:
    org.behappy: TRACE
    org:
      springframework:
        boot:
          actuate: DEBUG

