server:
  port: 8080

spring:
  application:
    name: maven-test
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      password:
      port: 6379
      timeout: 10000
      database: 0
      lettuce:
        pool:
          max-active: 600
          max-idle: 300
          max-wait: 10000


logging:
  level:
    org.behappy: debug

